### ISSUE TITLE
Mixin fail

### ISSUE THREAD

**Issue by some-du6e** [AnOpenSauceDev/Toast-Killer#2]
https://pastebin.com/Gjf4sjex

**Comment by AnOpenSauceDev** [comment]
are you on the right Toast-killer version? this mixin shouldn't fail unless another mod is overriding this behavior, or you're on the old non-`DrawContext` version.

**Comment by AnOpenSauceDev** [comment]
I think that this has something to do with a mod overwriting how toasts behave (i.e. forcing one to display), which is out of my control in that case.
